### ISSUE TITLE
analyse dashboard fails to parse Board.panels

### ISSUE THREAD

**Issue by yarix** [grafana/cortex-tools#242] opened 2022-03-01 12:10 UTC
* using cortex 0.10.7_windows_x86_64 dasboard analysys is broken for some dashboards (attached one example)
* dashboard downloaded from Grafana 8.4.1

```
C:\dev\cortex\cortextool>cortextool analyse dashboard "\Downloads\dash.json" --output=active.metrics.json
json: cannot unmarshal object into Go struct field Board.panels of type string for \Downloads\dash.json
```
[dash.zip](https://github.com/grafana/cortex-tools/files/8161443/dash.zip)

in other cases, i get:
* `cannot unmarshal object into Go struct field TemplateVar.templating.list.datasource of type string` - where all teplmate vars works good in Grafana.
* `unmarshal board: json: cannot unmarshal number 2.6666666666666665 into Go struct field Board.panels of type int` - the json file does not contain any 2.6666 number

**Comment by eamonryan** [comment] 2022-03-02 00:00
Duplicate of #241

**Closed by eamonryan** 2022-03-02 00:00 UTC
Labels: duplicate
